version: "3"

services:
##  Main application
#  go-restapi:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      - PORT=8080
#      - DATABASE_URL=postgres://postgres:postgres@pg/develop?sslmode=disable
#    depends_on:
#      - pg
#      - flyway

  pg:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'develop'
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.12
    ports:
      - 3081:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      PGADMIN_DEFAULT_EMAIL: 'al.shreyner@gmail.com'
    depends_on:
      - pg

# Service migrations
#  https://writeitdifferently.com/postgresql/flyway/2020/03/15/running-postgresql-and-flyway-with-docker-compose.html
  flyway:
    image: flyway/flyway:9.1.3
    command: migrate
    volumes:
      - ./db/migrations:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - pg
