version: "3"

services:
##  Application
#  go-restapi:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      - PORT=8080
#      - DATABASE_URL=postgres://postgres:postgres@pg/develop?sslmode=disable
#    depends_on:
#      - pg
#      - flyway

  pg:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'develop'
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:7.4
    ports:
      - 3081:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
      PGADMIN_DEFAULT_EMAIL: 'al.shreyner@gmail.com'
    depends_on:
      - pg
